spring:
  application:
    name: USER-SERVICE
  data:
    mongodb:
      uri: mongodb://admin:password@buy01:27017/admin
      database: buy01
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: user-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 3MB

kafka:
  topic:
    user-deleted: USER_DELETED

server:
  port: 8080
  ssl:
    enabled: false

eureka:
#  instance:
#    hostname: user-service
#    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: very-long-secret-key-string-with-at-least-32-chars