spring:
  application:
    name: MEDIA-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/buy01
      database: buy01
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: my-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 11MB

kafka:
  topic:
    product-deleted: PRODUCT_DELETED

server:
  port: 8082
  ssl:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: very-long-secret-key-string-with-at-least-32-chars
