spring:
  application:
    name: discovery-service

server:
  port: 8761
  ssl:
     enabled: true
     key-store: classpath:ssl/backend.p12
     key-store-password: password
     key-store-type: PKCS12
     key-alias: localhost

eureka:
  client:
    register-with-eureka: false   # Discovery itself does not register
    fetch-registry: false          # It doesnâ€™t fetch registry from anywhere
  server:
    enable-self-preservation: false  # optional, simplifies local dev
