spring:
  application:
    name: discovery

server:
  port: 8761

eureka:
#  instance:
#    hostname: discovery
#    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false  # For development, disable self-preservation mode


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
