spring:
  application:
    name: MEDIA-SERVICE
  data:
    mongodb:
      database: buy01
  cloud:
    inetutils:
      preferredNetworks:
        -"172."
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: my-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 11MB

kafka:
  topic:
    product-deleted: PRODUCT_DELETED

server:
  port: 8082
  address: 0.0.0.0
  ssl:
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: health,info
  server:
    port: 8082

eureka:
  instance:
    hostname: ${SERVICE_NAME}
    instance-id: ${SERVICE_NAME}:${server.port}
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

file:
  upload-dir: /app/uploads

jwt:
  secret: very-long-secret-key-string-with-at-least-32-chars

#jwt:
#  secret: ${JWT_SECRET}