spring:
  application:
    name: media-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/buy01
      database: buy01

server:
  port: 8446
  ssl:
    enabled: false
#    key-store: classpath:ssl/backend.p12
#    key-store-password: password
#    key-store-type: PKCS12
#    key-alias: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: very-long-secret-key-string-with-at-least-32-chars
