spring:
  application:
    name: product-service
  data:
    mongodb:
      database: buy01
  cloud:
    inetutils:
      preferredNetworks:
        -"172."
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: product-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 11MB

kafka:
  topic:
    user-deleted: USER_DELETED
    product-deleted: PRODUCT_DELETED
    product-updated: PRODUCT_UPDATED

server:
  port: 8081
  address: 0.0.0.0
  ssl:
    enabled: false
  error:
    # This will send the Java Exception trace to your frontend/Postman
    include-stacktrace: always
    include-message: always
management:
  endpoints:
    web:
      exposure:
        include: health,info
  server:
    port: 8081

eureka:
  instance:
    hostname: ${SERVICE_NAME}
    instance-id: ${SERVICE_NAME}:${server.port}
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

#jwt:
#  secret: very-long-secret-key-string-with-at-least-32-chars
#
jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    root: INFO
    # Change your project package to DEBUG to see more flow
    com.buy01.order: DEBUG
    # See exactly what Spring Web is doing when it fails
    org.springframework.web: DEBUG
    # See MongoDB interactions
    org.springframework.data.mongodb: DEBUG