spring:
  application:
    name: PRODUCT-SERVICE
  data:
    mongodb:
      uri: mongodb://admin:password@buy01:27017/buy01
      database: buy01
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: product-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  topic:
    user-deleted: USER_DELETED
    product-deleted: PRODUCT_DELETED

server:
  port: 8081
  ssl:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: very-long-secret-key-string-with-at-least-32-chars